export const haikus = [
	{ emojis: ['💰','🥇','🔭'], haiku: ["Golden coins glimmer,","Through the scope I see wealth grow,","Fortune now in hand."] },
	{ emojis: ['🎡','🧳','🤚🏻'], haiku: ["Twirling Ferris wheel,","Suitcases packed, ready to roam,","Hand waving goodbye."] },
	{ emojis: ['✋🏽','🖥','🕘'], haiku: ["Fingers and keyboard  ","The clock ticks as we work on  ","Hours melt away fast"] },
	{ emojis: ['🖊','🍑','🎨'], haiku: ["Ink and brush in hand,","Painting the curves of a peach,","A masterpiece born."] },
	{ emojis: ['🏴󠁧󠁢󠁷󠁬󠁳󠁿','🏧','🛳'], haiku: ["Welsh flag waving high,","A ship sets sail toward the bank,","Cymru calls me home."] },
	{ emojis: ['🧘🏻‍♀','🏴󠁧󠁢󠁳󠁣󠁴󠁿','📢'], haiku: ["In Scottish land's air,","Her voice calms and guides the soul,","Namaste, peace unfolds."] },
	{ emojis: ['👎🏾','👿','🥓'], haiku: ["Hateful thoughts arise","Bacon sizzles on the stove","Bad vibes to the brim"] },
	{ emojis: ['🥰','🕛','⌨️'], haiku: ["Love in real time,","Keyboard sounds, heartbeats in sync,","Hours slip away."] },
	{ emojis: ['👩🏽‍❤️‍💋‍👨🏼','🤷🏾','🀄'], haiku: ["Lovers lock in kiss,","Confused onlooker's question,","Game of chance, unsure."] },
	{ emojis: ['🐳','⛩️','👾'], haiku: ["Giant whale breaching,","Ancient temple rising high,","Aliens observe."] },
	{ emojis: ['💺','😸','🤫'], haiku: ["A seat occupied,","Silent cat pretends to sleep,","Peaceful tranquility."] },
	{ emojis: ['🥸','💰','🐟'], haiku: ["wearing a disguise,","fishing for fortune and wealth,","masks hide our intent."] },
	{ emojis: ['👨🏻‍❤‍💋‍👨🏽','✍🏾','🎀'], haiku: ["Two hearts intertwined,","Love knows no gender nor race,","A bow to seal it."] },
	{ emojis: ['🤙🏻','🗃️','☺️'], haiku: ["Hang loose, papers filed ","Happy in the organization ","Zen vibes in the mix"] },
	{ emojis: ['♂','⚜️','〰️'], haiku: ["Golden knight majestic,","Emblem of chivalry's grace,","Honour and glory."] },
	{ emojis: ['🗯️','🫂','🦹🏼‍♀️'], haiku: ["Loud voices collide,","Embrace between foes concealed,","Heroine prevails."] },
	{ emojis: ['🧜🏻','🚤','😋'], haiku: ["Mermaid on the boat,","Wind in hair and smile on face,","Joyful sea escape."] },
	{ emojis: ['❣','🤘🏽','🈲'], haiku: ["Symbols of the heart,","Rebel hand sign, and unknown,","Unfamiliar script."] },
	{ emojis: ['🙄','🏖️','🤔'], haiku: ["Eyes roll, thoughts ponder","Beach oasis, troubled mind","Answers hard to find"] },
	{ emojis: ['🔏','👎🏽','🤳🏼'], haiku: ["A lock clicks open,","Disapproval on the screen,","Selfie for no one."] },
	{ emojis: ['🏃‍♂️','🧘🏿‍♀️','☺'], haiku: ["Running and yoga,","Happy smiles on their faces,","Tranquil harmony."] },
	{ emojis: ['🍁','💕','🌅'], haiku: ["Autumn leaves falling,","Golden hues paint the skyline,","Love blooms at sunset."] },
	{ emojis: ['🏡','🛳️','🧷'], haiku: ["House on the shore's edge","Securely tied to the dock","Latches keep it safe"] },
	{ emojis: ['🏟','🦑','🫕'], haiku: ["In the stadium,  ","Spectators munch on strange fare,  ","Squid on their plates now."] },
	{ emojis: ['🦽','🪆','🛰'], haiku: ["On wheels or in space","Modes of transportation vast","Life's journey takes flight"] },
	{ emojis: ['🍎','🕊','🥈'], haiku: ["A silver bird flies,","Fruit falls softly to the ground,","Autumn's beauty blooms."] },
	{ emojis: ['🎥','♋','👨‍🌾'], haiku: ["Country man on screen,","Under the crab's sign he stands,","Harvest on his mind."] },
	{ emojis: ['💠','⛳','🤡'], haiku: ["A diamond in green,","Clown tees up for a round of play,","Summer's delight found."] },
	{ emojis: ['👊🏻','👋🏾','🤭'], haiku: ["Fist and palm collide","Mouth covered, a quiet laugh","A secret moment"] },
	{ emojis: ['👩🏽‍❤‍💋‍👨🏽','😮‍💨','😛'], haiku: ["Whispers of sweet love,  ","Tingling rush of stolen breaths,  ","Lips locked in delight."] },
	{ emojis: ['🧴','🏗️','⛩️'], haiku: ["The workers toil on","Heavy with sweat and effort","Amidst ancient shrine"] },
	{ emojis: ['🕤','©️','🏳‍🌈'], haiku: ["Hours tic away,","Rainbow flag in the wind waves,","Time for equality."] },
	{ emojis: ['💯','🪳','😷'], haiku: ["One hundred bugs fly","Masked face tries to repel them","Buzzing chaos reigns"] },
	{ emojis: ['🏳‍⚧','👨','🌸'], haiku: ["Gentle petals bloom  ","A man's heart with courage true  ","Transcending gender"] },
	{ emojis: ['🧍🏼‍♂','🤔','😁'], haiku: ["Lost in deep thought he,","Contemplating with slight doubt,","Brightened by a smile."] },
	{ emojis: ['♠','🔭','🥑'], haiku: ["A spade points below,","Telescope to reach the stars,","Avocado dreams."] },
	{ emojis: ['🕛','🤧','🏬'], haiku: ["Sneezing at the store,","Time ticks by, endless aisles loom,","Day crawls to its close."] },
	{ emojis: ['🀄','🧋','🌹'], haiku: ["Mahjong tiles face down,","Bitter tea, sweet rose petals,","Silent game begins."] },
	{ emojis: ['♀️','🥳','📟'], haiku: ["A woman celebrates","Her pager beeps with delight","Messages of joy"] },
	{ emojis: ['❤‍🔥','✊🏼','🪤'], haiku: ["Passion's fire burning,","Hands clasped in defiance strong,","Trapped by heart's desire."] },
	{ emojis: ['🙂','🦀','💇🏻‍♀️'], haiku: ["A crab on the shore,","Watching a hairstylist cut","Strands in the sea breeze."] },
	{ emojis: ['🤓','⛵','🙉'], haiku: ["Nerd on a boat sails,","Monkey chatter fills the air,","Curiosity."] },
	{ emojis: ['🤩','👈','😂'], haiku: ["Excitement within,","laughter fills the air with joy,","pure bliss surrounds us."] },
	{ emojis: ['👤','🗝️','🏴󠁧󠁢󠁷󠁬󠁳󠁿'], haiku: ["Lonely person, seeks ","Key to unlock their heart's depth ","In Wales, they find peace"] },
	{ emojis: ['📸','🏘','☝🏾'], haiku: ["Camera clicks the view,","Houses standing tall and proud,","A lone finger points."] },
	{ emojis: ['🩸','📞','☺'], haiku: ["Answer the phone call,","A smile on your face for all,","Blood stains the handset."] },
	{ emojis: ['🐍','🏡','🤭'], haiku: ["Slithering sneaky,","Snake makes home in secret place,","Surprise awaits all."] },
	{ emojis: ['😓','🈂️','😼'], haiku: ["Overwhelmed with stress","The perfect mask: a grimace","Eyes dart, claws extend."] },
	{ emojis: ['🫂','⛪','⛵'], haiku: ["Embraced by the church,","A boat sets course to the sea,","Beneath blue skies free."] },
	{ emojis: ['📯','🐉','🤭'], haiku: ["A regal horn sounds,","Dragon peaks over the cliff,","Hiding with a smile."] },
	{ emojis: ['😁','😙','🥚'], haiku: ["Joyful smiles and kiss","Eggs in nests of hopeful bliss","Nature's springtime gift"] },
	{ emojis: ['👻','®','🪡'], haiku: ["A ghostly vision, ","Embroidering with needle, ","A phantom seamstress."] },
	{ emojis: ['⚰','🍌','🐌'], haiku: ["a snail crosses by","a rotten banana peel","tombstone stands silent"] },
	{ emojis: ['🥂','😿','🍮'], haiku: ["Champagne glasses clink","Sorrowful kitty watches","Dessert uneaten."] },
	{ emojis: ['😔','🥳','🤝'], haiku: ["Heavy hearted sighs,","Joyous festivities near,","Joining hands for now."] },
	{ emojis: ['🔮','🤟🏼','🤚🏾'], haiku: ["Crystal ball shimmers","Fingers rock in cool rhythm","Fortune lies ahead"] },
	{ emojis: ['🤷🏻‍♀','😪','😩'], haiku: ["Shoulders rise and fall,","Confused and tired, heavy sighs,","Lost in thoughts and woes."] },
	{ emojis: ['🎡','🇫🇷','🧦'], haiku: ["A Ferris wheel high","France's Eiffel tower nigh","Socks on feet, snugly"] },
	{ emojis: ['👨🏻‍❤‍💋‍👨🏻','🎱','🏷️'], haiku: ["Cuddled in his arms","The billiard ball clacks and rolls","Love, labeled illegal."] },
	{ emojis: ['💷','🕥','🦵🏽'], haiku: ["Pounds trickle away,","Time ticks by relentlessly,","Legs carry us on."] },
	{ emojis: ['🪶','⚱️','🗣'], haiku: ["Feather whispers soft,","Echoes from within the urn,","Spoken from the past."] },
	{ emojis: ['🪢','🚒','🈴'], haiku: ["Red truck rushes by","Tangled rope knotted inside","Bound by tradition"] },
	{ emojis: ['⚾','🌏','👈🏼'], haiku: ["Baseball's globe is round","Under the blue sky it flies","Homerun, we all cheer"] },
	{ emojis: ['🥵','⛑','🧳'], haiku: ["Sweat drips down my face,","Heat beats upon my head hard,","Helmet shields the burn."] },
	{ emojis: ['👤','🦥','🅾️'], haiku: ["Human, sloth, letter O","Strange trio meets in nature's flow","Peaceful coexistence"] },
	{ emojis: ['🕥','🤗','😁'], haiku: ["Clock ticks once again  ","Gleeful smiles all around me  ","Time to enjoy life"] },
	{ emojis: ['🎡','🛥','😊'], haiku: ["The wheel and boat glide","Into the sky and water","Joyful hearts abide"] },
	{ emojis: ['⏱️','🧟‍♀','🏢'], haiku: ["Seconds slowly tick,","Undead roam the deserted halls,","Empty office looms."] },
	{ emojis: ['🗨','👺','🖖🏿'], haiku: ["Flames of anger burn","A demon's voice echoes loud","Vulcan peace prevails"] },
	{ emojis: ['😔','🖐','🏵'], haiku: ["Sadness in my heart","Hand reaches out for a flower","Hope for better days"] },
	{ emojis: ['🕜','😂','🍢'], haiku: ["Time ticks, laughter roars,","Sizzling skewers on charcoal,","Moments to cherish."] },
	{ emojis: ['🙁','🛥','⁉️'], haiku: ["Stormy waters heave,","Sadness grips this lonely ship,","Questions on the wind."] },
	{ emojis: ['🪱','🛥','🌭'], haiku: ["Worms in the bait box","Boats float calmly on the lake","Hot dogs on the grill"] },
	{ emojis: ['🏺','👺','🤭'], haiku: ["A vase on the shelf,","A demon's face inside peeks,","Mischievous laughter."] },
	{ emojis: ['😻','Ⓜ','🪟'], haiku: ["A cat by the window","Watching raindrops on the glass","Peaceful afternoon"] },
	{ emojis: ['♥️','✋🏿','↙️'], haiku: ["Heart and hand unite,","Love flows down and to the left,","Two in harmony."] },
	{ emojis: ['🚿','😴','🐿️'], haiku: ["In the shower, steam","Sleepy squirrel peers through the glass","Nature's view obscured"] },
	{ emojis: ['🧑🏾‍⚖','🍍','🗺️'], haiku: ["Justice in motion ","A pineapple on the map ","The world awaits change"] },
	{ emojis: ['😆','🏮','🤔'], haiku: ["Laughing with a doubt","The lantern casts a soft glow","Puzzled thoughts arise"] },
	{ emojis: ['🙉','📽️','🏑'], haiku: ["Monkey watches game","Hockey sticks hit the puck hard","Silent movie star"] },
	{ emojis: ['🔬','👎🏾','👐🏿'], haiku: ["Microscope reveals","Tainted truth, hands held up high","Science, justice denied"] },
	{ emojis: ['🕚','🔏','🇦🇴'], haiku: ["Tick-tock goes the clock","Secure lock keeps treasures safe","Angola awaits"] },
	{ emojis: ['🥸','✳','🍶'], haiku: ["Disguised as someone else,","Sipping sake with a smile,","Mischief in the air."] },
	{ emojis: ['🚷','🧳','🥸'], haiku: ["Do not cross the line","With luggage and disguise on","Masks cannot hide all."] },
	{ emojis: ['🎭','🤮','🤔'], haiku: ["Theater masks hide","All thoughts and feelings inside,","Vomit stains surprise."] },
	{ emojis: ['🥵','🧋','🤷🏽‍♂️'], haiku: ["Sweat drips down my face  ","Thirsty for a cool refreshment  ","Uncertain what to do"] },
	{ emojis: ['🏴󠁧󠁢󠁷󠁬󠁳󠁿','😿','🌹'], haiku: ["Welsh land of sorrow,","A rose in tears, wilted and grey,","Lost love, a heartache."] },
	{ emojis: ['🧖','🤯','🕸️'], haiku: ["Steam and sweat rising,","Mind and senses overwrought,","A tangled web spun."] },
	{ emojis: ['🏗','🙅🏻','🤣'], haiku: ["Construction halted ","'Nope, not today', she chuckles ","Laughter echoes loud"] },
	{ emojis: ['🧲','🏁','🏭'], haiku: ["Magnet draws iron","Flag waves high in the factory","Industry hums on"] },
	{ emojis: ['👿','🛎️','👹'], haiku: ["Evil bells do chime,","Monstrous beings lurk nearby,","Fearful souls take flight."] },
	{ emojis: ['🐛','🎨','🙈'], haiku: ["Crawling caterpillar,","Colorful paints decorate,","Monkey watches close."] },
	{ emojis: ['🐸','🍢','🥲'], haiku: ["green frog in the pond ","grilled skewers sizzling on fire ","tearful goodbyes shared"] },
	{ emojis: ['🔊','😍','🧑🏻'], haiku: ["Loud sounds fill the air,","Heart awakens with delight,","Love for a person."] },
	{ emojis: ['6️⃣','🪙','🔏'], haiku: ["Six coins shine and gleam,","A key unlocks their secrets,","Treasure in my grasp."] },
	{ emojis: ['🛎','👨🏿‍🦽','😇'], haiku: ["Sound echoes through halls,","A man, determined, rolls on,","Angels watch with love."] },
	{ emojis: ['🤘🏾','🧦','🐋'], haiku: ["Sign of rock and roll","Socks atop whale's spout arise","Harmony in strange"] },
	{ emojis: ['🥽','🌯','🤚🏼'], haiku: ["Goggles on my face","Burrito in my hand's hold","Summer adventure."] },
	{ emojis: ['👎🏻','🤓','🤭'], haiku: ["Disapproving frown,","Nerdiness and a sly grin,","Secrets stay hidden."] },
	{ emojis: ['⚓','🛕','🦪'], haiku: ["Ancient temple stands,","Anchored by the sea's vastness,","Oysters adorn shore."] }
];
